-- 시퀀스 생성
CREATE SEQUENCE SEQ_BOARD NOCACHE NOCYCLE;

-- 시퀀스 삭제
DROP SEQUENCE SEQ_BOARD;

-- 테이블 생성
CREATE TABLE BOARD(
    ID            NUMBER    -- NOT NULL / UNIQUE / PRIMARY KEY /
    , TITLE       VARCHAR2(100)
    , CONTENT     VARCHAR2(4000)
);

-- 테이블 삭제
DROP TABLE BOARD;

-- 게시글 목록 조회
SELECT * FROM BOARD;

-- 게시글 작성
INSERT INTO BOARD(ID, TITLE, CONTENT) VALUES(1, 'TTT', 'CCC');

-- 게시글 수정
UPDATE BOARD SET TITLE = 'TITLE01' WHERE ID = 1;

-- 게시글 삭제
DELETE BOARD WHERE ID =1;

COMMIT;