# -*- coding: utf-8 -*-
"""DL_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-GA6_ff4KHmpw-mdx56ubyTkKivPWECE

# 신경망 (순전파, 손실함수, 경사하강)

### 뉴런 1개
"""

import torch

x = torch.tensor([1.,2.,3.]) # 입력값
w = torch.tensor([0.2,0.8,-0.5]) # 가중치
b = torch.tensor(0.1) # 편향치

z = (x * w).sum() + b
print(z.item())

# y = torch.sigmoid(z)
y = torch.sigmoid(torch.tensor(10000))
print(y.item())

"""### 뉴런 쌓기"""

import torch

x = torch.tensor([[1.,2.,3.]])
w = torch.rand(3,4)
b = torch.rand(4)

z = x @ w + b
y = torch.relu(z)
print(y)
print(y.shape)

"""### 활성화 함수"""

import torch

z = torch.tensor([-2,-1,0,1,2.0])

print('sigmoid : ', torch.sigmoid(z))
print('relu : ', torch.relu(z))
print('tanh : ', torch.tanh(z))

"""### 손실함수

### 교차 엔트로피

### 경사하강법

### 역전파

### 합성곱
"""