# -*- coding: utf-8 -*-
"""DL_00.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-e2_U0dyxkmIZ4TgMNta-j70_N2lEjD1

### GPU 확인
"""

import torch
print(torch.__version__)
print(torch.cuda.is_available())

"""### 텐서 만들기"""

# x = torch.tensor([[1,2,3],[4,5,6]])
# x = torch.zeros(2,3)
# x = torch.ones(2,3)
x = torch.rand(2,3)
print(x)

x = torch.tensor([1.,2,3])
y = torch.tensor([4,5,6])

print(x.sum())

A = torch.rand(2,3)
B = torch.rand(3,4)
result = (A @ B)
print(result.shape)
print(result)

"""### 텐서를 GPU로 보내기"""

sample = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x = torch.rand(3,3)
y = torch.rand(3,3)

x = x.to(sample)
y = y.to(sample)

print(x + y)